# These are supported funding model platforms

paypal: https://paypal.me/DonsBot

cashapp: $DonArrington

Bitcoin: bc1qwmeqa49gg3hwv50hs8snk7wzufjwal8s2mt6ep

Dogecoin: D8tY1szrUwaLsW2nNZJtHctf57fdvQorYg

Litecoin: ltc1qxqhnh3w3sn2sqwft4cy8zjmtdjx5hfl7m43jlw

Ethereum: 0x8De3E8dD1B8E7866053d403081d83aF64195e75f
